# Generated by Django 2.2 on 2020-05-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70, null=True, verbose_name='Título')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creación De La Tarea')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created'],
            },
        ),
    ]
